accounts/urls.py
from django.conf.urls import url
from accounts import views

urlpatterns = [
    url(r'^register', views.registration, name='registration'),
    url(r'^login', views.login_user, name='login'),
    url(r'^account', views.account, name='account'),
    url(r'^logout', views.logout_user, name='logout')
]

posts/urls.py
from django.conf.urls import url
from posts import views

app_name = 'posts'

urlpatterns = [
    #index page
    url(r'^(?:page/(?P<page>\d+)/)?$', views.IndexView.as_view(), name='paginated_posts'),
    url(r'^add', views.add_post, name='add_post'),
    url(r'^edit/(?P<id>\d+)', views.edit_post, name='edit_post'),
    # #/post-slug-here
    url(r'^(?P<slug>[\w-]+)/$', views.ViewPostView.as_view(), name='view_post'),
    url(r'^search', views.search_post, name='search_post'),
]

webpicnic/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('posts.urls')),
    url(r'^', include('accounts.urls'))
]

accounts/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

posts/models.py
from __future__ import unicode_literals
from django.template.defaultfilters import slugify
from django.conf import settings

from django.db import models

# Create your models here.

class Tag(models.Model):
	tag_name = models.CharField(max_length=50)
	tag_description = models.CharField(max_length=250)

	def __str__(self):
		return self.tag_name
		
class Post(models.Model):
	title = models.CharField(max_length=250)
	content = models.TextField()
	date_created = models.DateField(auto_now_add=True)
	author = models.ForeignKey(settings.AUTH_USER_MODEL)
	published = models.BooleanField('Published')
	slug = models.SlugField(max_length=100)
	date_updated = models.DateField(null=True)
	tags = models.ManyToManyField(Tag)

	def __str__(self):
		return "{}".format(self.title)

	def save(self, *args, **kwargs):
		self.slug = slugify(self.title)
		super(Post, self).save(*args, **kwargs)

	class Meta:
		ordering = ('-date_created',)

accounts/forms.py
from django import forms

class RegisterForm(forms.Form):
	#firstname = forms.CharField(max_length=100, label="Firstname")
	#lastname = forms.CharField(max_length=100, label="Lastname")
	email = forms.EmailField(
		max_length=100,
		label="Email address",
		widget=forms.TextInput(attrs={'class': 'form-control margin-bottom-10',})
	)
	username = forms.CharField(
		max_length=20,
		label="Username",
		widget=forms.TextInput(attrs={'class': 'form-control margin-bottom-10',})
	)
	password = forms.CharField(
		min_length=6,
		label="Password",
		widget=forms.PasswordInput(attrs={'class': 'form-control margin-bottom-10',})
	)

class LoginForm(forms.Form):
	username = forms.CharField(
		max_length=20,
		label="Username",
		widget=forms.TextInput(attrs={'class': 'form-control margin-bottom-10',})
	)
	password = forms.CharField(
		min_length=6,
		label="Password",
		widget=forms.PasswordInput(attrs={'class': 'form-control margin-bottom-10',})
	)

posts/forms.py
from django import forms
from django.forms import ModelForm
from .models import Post

class AddPostForm(ModelForm):
	class Meta:
		model = Post
		fields = ['title', 'content', 'author', 'published']

class EditPostForm(ModelForm):
	class Meta:
		model = Post
		fields = ['title', 'content', 'author', 'published']

accounts/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm, LoginForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from posts.models import Post

# Create your views here.
def registration(request):
    if request.method == 'POST':
        #Create form instance
        form = RegisterForm(request.POST)
        if form.is_valid():
            #Get all data from form
            email = form.cleaned_data['email']
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            check_username = User.objects.filter(username=username).exists()
            if check_username is True:
                return_data = {'form': form, 'error': 'A user with this username already exists.'}
            else:
                user = User.objects.create_user(username, email, password)
                auth_user = authenticate(username=username, password=password)
                if auth_user is not None:
                    login(request, user)
                    return redirect('account')
    else:
        form = RegisterForm()
        return_data = {'form': form }
    #Return to registration page
    return render(request, 'accounts/register.html', return_data)

def login_user(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('/', user=user)
            else:
                return_data = {'form': form, 'error': 'Can\'t login account.'}
                return render(request, 'accounts/login.html', return_data)
    else:
        form = LoginForm()
        return_data = {'form': form}
        return render(request, 'accounts/login.html', return_data)

def account(request):
    if request.user.is_authenticated:
        posts_list = Post.objects.filter(author=request.user.id)
        return_data = {'posts':posts_list}
        return render(request, 'accounts/account.html', return_data)
    else:
        return redirect('/')

def logout_user(request):
    logout(request)
    return redirect('/')

posts/views.py
from django.shortcuts import render, redirect
from .models import Post
from .forms import AddPostForm, EditPostForm
from datetime import datetime
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.http import Http404
from django.views.generic import TemplateView

# Create your views here.

class IndexView(TemplateView):
    template_name = 'posts/index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        posts_list = Post.objects.filter(published=True)
        paginator = Paginator(posts_list, 5)
        page = kwargs['page']
        try:
            paginated_posts = paginator.page(page)
        except PageNotAnInteger:
            paginated_posts = paginator.page(1)
        except EmptyPage:
            paginated_posts = paginator.page(paginator.num_pages)
        context['posts'] = paginated_posts
        return context

class ViewPostView(TemplateView):
    template_name = 'posts/post.html'

    def get_context_data(self, **kwargs):
        context = super(ViewPostView, self).get_context_data(**kwargs)
        post = Post.objects.get(slug=kwargs['slug'])
        context['post'] = post
        return context

def add_post(request):
    if request.method == 'POST':
        form = AddPostForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/account')
    else:
        form = AddPostForm()
        return_data = {'form':form, 'author':request.user.id}
        return render(request, 'posts/add-post.html', return_data)

def edit_post(request, id):
    if request.method == 'POST':
        post = Post.objects.get(id=id)
        post.title = request.POST.get('title')
        post.content = request.POST.get('content')
        published = request.POST.get('published')
        post.date_updated = datetime.now()
        if published is not None:
            post.published = True
        else:
            post.published = False
        post.save()
        return redirect('account')
    else:
        form = EditPostForm()
        post = Post.objects.get(id=id)
        return_data = {'form':form, 'post':post, 'author': request.user.id}
        return render(request, 'posts/edit-post.html', return_data)

def search_post(request):
    try:
        if request.GET.get('s'):
            s = request.GET.get('s')
            posts_list = Post.objects.filter(Q(title__contains=s) | Q(content__contains=s))
            return_data = {'posts': posts_list}
        elif request.GET.get('s_date'):
            search_date = datetime.strptime(request.GET.get('s_date'), '%Y-%m-%d')
            posts_list_by_date = Post.objects.filter(date_created=search_date)
            return_data = {'posts': posts_list_by_date}
        else:
            posts = Post.objects.all()
            return_data = {'posts':posts}
    except Post.DoesNotExist:
        raise Http404('No post matched your query')
    return render(request, 'posts/search.html', return_data)

templates/accounts/account.html
{% extends 'includes/base.html' %}
{% block content %}

<div class="container">
	<div class="row">
		<div class="col-sm-12 col-md-8">
			<a href="/add" class="btn btn-default btn-sm pull-right">Add a new post</a>
			<br>
			{% if posts %}
				<ul>
					{% for post in posts %}
						<hr>
						<a href="{{ post.slug }}"><h3>{{ post.title }}</h3></a>
						<small>{{ post.date_created }} | Updated: {{ post.date_updated }} | by {{post.author}}</small> | 
						{% if post.published %}
							<small><i>Published</i></small>
						{% else %}
							<small><i>Draft</i></small>
						{% endif %}
						<p>{{ post.content | truncatechars:300 }} <a href="edit/{{ post.id }}" class="btn btn-warning btn-sm">Edit</a></p>
					{% endfor %}
				</ul>
			{% else %}
				<h5>No posts here!</h5>
			{% endif %}
		</div>
		<div class="col-sm-12 col-md-4">
			{% include 'includes/sidebar.html' %}
		</div>
	</div>
</div>

{% endblock %}

templates/accounts/login.html
{% extends 'includes/base.html' %}
{% block content %}
<div class="container">
<br><br>
	<div class="row">
		<div class="col-sm-12 col-md-4 col-md-offset-4 col-lg-4 col-lg-offset-4">
			<div class="well">
				<h3>Login</h3>
				{% if error%}
					<div class="alert alert-warning">{{error}}</div>
				{% endif %}
				<form action="/login" method="post">
					{% csrf_token %}
					{{form}}
					<div class="form-group">
						<div class="row">
							<div class="col-sm-12">
								<button type="submit" class="btn btn-primary btn-block">Login</button><br>
							</div>
							<div class="col-sm-12">
								<a href="register" class="btn btn-success btn-block">Register</a><br>
							</div>
							<div class="col-sm-12">
								<a href="/" class="btn btn-default btn-block">Home</a>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock %}

templates/accounts/register.html
{% extends 'includes/base.html' %}
{% block content %}
<div class="container">
<br><br>
	<div class="row">
		<div class="col-sm-12 col-md-4 col-md-offset-4 col-lg-4 col-lg-offset-4">
			<div class="well">
				<h3>Register an account</h3>
				<br>
				{% if error%}
					<div class="alert alert-warning">{{error}}</div>
				{% endif %}
				<br>
				<form action="/register" method="post">
					{%csrf_token%}
					{{form}}
					<div class="form-group">
						<div class="row">
							<div class="col-sm-12">
								<button type="submit" class="btn btn-primary btn-block">Register</button><br>
							</div>
							<div class="col-sm-12">
								<a href="login" class="btn btn-success btn-block">Login</a><br>
							</div>
							<div class="col-sm-12">
								<a href="/" class="btn btn-default btn-block">Home</a>
							</div><br>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock %}

templates/includes/base.html
{% include 'includes/header.html' %}
{% include 'includes/navbar.html' %}

{% block content %}
{% endblock %}

{% include 'includes/footer.html' %}

templates/includes/footer.html
</body>
{% load static %}
<script type="text/javascript" src="{% static 'js/jquery-3.2.1.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
</html>

templates/includes/header.html
<!DOCTYPE html>
<html>
<head>
	<title>Webpicnic</title>
	{% load static %}
	<link rel="stylesheet" href="{% static 'css/paper.css' %}">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

templates/includes/navbar.html
<nav class="navbar navbar-inverse navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="/">Webpicnic</a>
	    </div>
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav navbar-right">
					{% if user.is_authenticated %}
						<li><a href="/account">Account</a></li>
						<li><a href="/logout">Logout</a></li>
					{% else %}
						<li><a href="/login">Login</a></li>
						<li><a href="/register">Register</a></li>
					{% endif %}
				</ul>
				<form class="navbar-form navbar-right" role="search" action="/search" method="get">
					<div class="form-group">
						<input type="text" class="form-control" placeholder="Type something here" name="s">
					</div>
					<button type="submit" class="btn btn-default">Search</button>
				</form>
	    </div>
	</div>
</nav><br><br><br><br>

templates/includes/sidebar.html
<div class="well">
	<p>Search by date</p>
	<form action="/search" method="get">
		<input type="date" class="form-control" name="s_date"><br>
		<button type="submit" class="btn btn-success">Search</button>
	</form>
</div>

templates/posts/add-post.html
{% extends 'includes/base.html' %}
{% block content %}

<div class="container">
	<div class="row">
		<div class="col-sm-12 col-md-8">
			<a href="/account" class="btn btn-success pull-right">Back</a>
			<h3>Add a new post</h3>
			<div class="well">
				<form action="/add" method="post">
					{% csrf_token %}
					<div class="form-group">
						<label class="control-label">{{form.title.label}}</label>
						<input id="id_title" maxlength="250" name="title" type="text" required="" class="form-control">
					</div>
					<div class="form-group">
						<label class="control-label">{{form.content.label}}</label>
						<textarea cols="40" id="id_content" name="content" rows="10" required="" class="form-control"></textarea>
					</div>
					<div class="form-group">
						<input name="author" type="hidden" required="" value="{{author}}">
					</div>
					<div class="form-group">
						{{form.published}} Check to publish. Leave unchecked to save as draft
					</div>
					<div class="form-group">
						<button type="submit" class="btn btn-primary">Add post</button>
					</div>
				</form>
			</div>
		</div>
		<div class="col-sm-12 col-md-4">
		</div>
	</div>
</div>

{% endblock %}

templates/posts/edit-post.html
{% extends 'includes/base.html' %}
{% block content %}

<div class="container">
	<div class="row">
		<div class="col-sm-12 col-md-8">
			<a href="/account" class="btn btn-success pull-right">Back</a>
			<h3>Edit this post</h3>
			<div class="well">
				<form action="/edit/{{post.id}}" method="post">
					{% csrf_token %}
					<div class="form-group">
						<label class="control-label">{{form.title.label}}</label>
						<input id="id_title" maxlength="250" name="title" type="text" required="" class="form-control" value="{{post.title}}">
					</div>
					<div class="form-group">
						<label class="control-label">{{form.content.label}}</label>
						<textarea cols="40" id="id_content" name="content" rows="10" required="" class="form-control">{{post.content}}</textarea>
					</div>
					<div class="form-group">
						<input name="author" type="hidden" required="" value="{{author}}">
					</div>
					<div class="form-group">
						<input id="id_published" name="published" type="checkbox" {% if post.published%}checked{% endif %}> Check to publish. Leave unchecked to save as draft
					</div>
					<div class="form-group">
						<button type="submit" class="btn btn-primary">Update post</button>
					</div>
				</form>
			</div>
		</div>
		<div class="col-sm-12 col-md-4">
		</div>
	</div>
</div>

{% endblock %}

templates/posts/index.html
{% extends 'includes/base.html' %}
{% block content %}

<div class="container">
	<div class="row">
		<div class="col-sm-12 col-md-8">
			{% if posts %}
				{% for post in posts %}
					<a href="{% url 'posts:view_post' post.slug %}"><h3>{{ post.title }}</h3></a>
						<small>{{ post.date_created }} | Updated: {{ post.date_updated }} | by {{post.author}}</small>
						<p>{{ post.content | truncatechars:300 }}</p>
					<hr>
				{% endfor %}
				{% if posts.has_other_pages %}
					<ul class="pager">
						{% if posts.has_previous %}
							<li class="previous"><a href="/page/{{posts.previous_page_number}}"">&larr; Newer</a></li>
							{% endif %}
							<span class="current">
								<p>Page {{posts.number}} of {{posts.paginator.num_pages}}.</p>
							</span>
							{% if posts.has_next %}
								<li class="next"><a href="/page/{{posts.next_page_number}}">Older &rarr;</a></li>
							{% endif %}
					</ul>
				{% endif %}
			{% else %}
				<h5>No posts here!</h5>
			{% endif %}
		</div>
		<div class="col-sm-12 col-md-4">
			{% include 'includes/sidebar.html' %}
		</div>
	</div>
</div>

{% endblock %}

templates/posts/post.html
{% extends 'includes/base.html' %}
{% block content %}

<div class="container">
	<div class="row">
		<div class="col-sm-12 col-md-8">
			{% if post %}
				<h3>{{post.title}}</h3>
				<small>{{ post.date_created }} | Updated: {{ post.date_updated }} | by {{post.author}}</small><hr>
				<p>{{ post.content }}</p>
			{% endif %}
		</div>
		<div class="col-sm-12 col-md-4">
			{% include 'includes/sidebar.html' %}
		</div>
	</div>
</div>

{% endblock %}

templates/posts/search.html
{% extends 'includes/base.html' %}
{% block content %}

<div class="container">
	<div class="row">
		<div class="col-sm-12 col-md-8">
			{% if posts %}
				{% for post in posts %}
					<a href="{{ post.slug }}"><h3>{{ post.title }}</h3></a>
						<small>{{ post.date_created }} | Updated: {{ post.date_updated }} | by {{post.author}}</small>
						<p>{{ post.content | truncatechars:300 }}</p>
					<hr>
				{% endfor %}
			{% else %}
				<h3>No results matched your search</h3>
			{% endif %}
		</div>
		<div class="col-sm-12 col-md-4">
			{% include 'includes/sidebar.html' %}
		</div>
	</div>
</div>

{% endblock %}